### ISSUE TITLE
Resize canvas should be supported

### ISSUE THREAD

**Issue by ryansturmer** [ShopBotTools/Handibot-GCodeViewer#1]
It should be possible to resize the element rendering the g-code.  Currently the SetSize() method doesn't update the aspect of the combined camera properly.

This was done previously here:

https://github.com/FabMo/FabMo-Engine/blob/4112f1bcb83c9697b36df782c5c0eaadc88fe8fb/dashboard/apps/previewer/index.html#L53-L60

Though this technique only works for the perspective camera, not the orthographic one.

**Comment by Alex-Canales** [comment]
It is now possible to resize the canvas. When you resize the element rendering the g-code, you have to call the function "resize(width, height)" of the Viewer class.
https://github.com/ShopBotTools/Handibot-GCodeViewer/blob/prestable2/viewer.js#L40

It handles the camera (we use a combinedCamera) and the gui display.
