### ISSUE TITLE
G-Code display covers controls

### ISSUE THREAD

**Issue by ryansturmer** [ShopBotTools/Handibot-GCodeViewer#2]
The G-Code display seems to cover some of the controls.  It would be nice if the G-Code display was optional, in any case.

![screen shot 2015-08-14 at 9 58 59 am](https://cloud.githubusercontent.com/assets/1383181/9275451/2bc182d8-426b-11e5-87d3-9790500fa6bf.png)

**Comment by Alex-Canales** [comment]
Did you take a screenshot of the whole previewer or just from the middle to the right?
The interface should look like this:
![interface](https://cloud.githubusercontent.com/assets/12187544/9310740/1fc4d3e8-4501-11e5-80c5-65aff9f26a6d.png)
The GCode should be displayed in the middle of the screen. Moreover, you should be able to toggle the display of the GCode (as you can see from my screenshot, no GCode is displayed).
