### ISSUE TITLE
Animation hangs on g-code file

### ISSUE THREAD

**Issue by ryansturmer** [ShopBotTools/Handibot-GCodeViewer#3]
I have encountered the animation stopping unexpectedly in the g-code file indicated:

https://gist.github.com/ryansturmer/5753fd67cb0968f6e64d

It appears to stop the animation here:

![screen shot 2015-08-20 at 10 51 11 am](https://cloud.githubusercontent.com/assets/1383181/9386425/6e158b62-4729-11e5-8c2b-a46acd79a011.png)

**Comment by Alex-Canales** [comment]
The problem was caused by the function checking if two value are nearly equal. It worked well with positive number but not with negative numbers.
Corrected [in this commit](https://github.com/ShopBotTools/Handibot-GCodeViewer/commit/ddbf6da52f0ba0799f889b208951fd4694fa3a68).
