### ISSUE TITLE
Arrows/text should scale with the job

### ISSUE THREAD

**Issue by ryansturmer** [ShopBotTools/Handibot-GCodeViewer#4]
The axis arrows and text should probably scale with the job size.  For instance, if I were carving something that was very small <1inch, the arrows and text that indicate the job size and the axis directions would appear HUGE.  When a g-code file is loaded, should the arrow dimensions and the text in the 3d view be scaled to make them look reasonable in the context of the job scale?

Example:

This looks fine:
![screen shot 2015-08-20 at 10 53 20 am](https://cloud.githubusercontent.com/assets/1383181/9386640/6a15d3b8-472a-11e5-8a59-5299a163690f.png)

But when you add a relatively small job:
![screen shot 2015-08-20 at 10 53 44 am](https://cloud.githubusercontent.com/assets/1383181/9386644/7338752c-472a-11e5-8d06-88056234da99.png)

The arrows and text would look better if they were more like this size:
![rescaled](https://cloud.githubusercontent.com/assets/1383181/9386652/7e082e02-472a-11e5-8da7-325dcde95ffd.png)

**Comment by Alex-Canales** [comment]
I have changed the display.
![selection_001](https://cloud.githubusercontent.com/assets/12187544/9390769/afd8bc5c-4762-11e5-85be-05d08de008af.png)
Even if it is still big, I think it is correct. But since I was always working with the huge old display, I am not very objective about the new display...

**Comment by ryansturmer** [comment]
That looks better: 

1) Does it scale with the bounds of the job?
2) Did you scale the cone used in the job animation as well?

I wonder if we should do the working bounds text in the color for that axis (red for x, etc)

**Comment by Alex-Canales** [comment]
1) Yes
2) It is hard coded, it will not scale.

For the working bound text, I think there is no use to change the colour.
