### ISSUE TITLE
Pan controls on mac

### ISSUE THREAD

**Issue by ryansturmer** [ShopBotTools/Handibot-GCodeViewer#5]
Can pan be enabled with something other than the middle button?  On systems with no middle button, a shift+drag or ctrl+drag or meta+drag would be nice.

-R

**Comment by Alex-Canales** [comment]
It is now possible to pan by using shift + left mouse button.

By the way, the true term for panning is to rotate the camera on the horizontal plan, here we do trucking (apparently, I am a neophyte in this field). I don't know why they did not why this term for the Orbit Controls.

**Comment by ryansturmer** [comment]
Thanks for fixing, and thanks for the info!  I did not know the difference between panning and trucking.
